# Generated by Django 5.2.7 on 2025-12-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0002_remove_category_parent_modelproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='category',
            field=models.ManyToManyField(related_name='models', to='malias.category', verbose_name='Категории'),
        ),
    ]
