# Generated by Django 5.2.9 on 2025-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0004_order_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон номер клиента')),
                ('text', models.CharField(max_length=400, verbose_name='Запрос клиента')),
                ('file', models.FileField(blank=True, null=True, upload_to='contact/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Запрос клиента',
                'verbose_name_plural': 'Запросы клиентов',
            },
        ),
    ]
