# Generated by Django 5.2.9 on 2026-01-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Запрос клиента'),
        ),
    ]
