# Generated by Django 5.2.9 on 2026-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0006_alter_contact_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Эл. Почта клиента'),
            preserve_default=False,
        ),
    ]
