# Generated by Django 5.2.9 on 2026-01-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0007_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='malias.order', verbose_name='Заказ'),
        ),
    ]
