# Generated by Django 5.2.9 on 2026-01-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0009_deliverymethod_paymentmethod_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'verbose_name': 'Методы Доставок', 'verbose_name_plural': 'Метод Доставки'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Методы Оплаты', 'verbose_name_plural': 'Метод Оплаты'},
        ),
    ]
