# Generated by Django 5.2.9 on 2026-01-07 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0010_alter_deliverymethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.deliverymethod'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.paymentmethod'),
        ),
    ]
