# Generated by Django 5.2.9 on 2026-01-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0011_remove_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.deliverymethod', verbose_name='Метод Доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='malias.paymentmethod', verbose_name='Метод Оплаты'),
        ),
    ]
