# Generated by Django 5.2.9 on 2026-01-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malias', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='malias.product'),
            preserve_default=False,
        ),
    ]
